version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: micro_user
      POSTGRES_PASSWORD: Thanishka@5
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U micro_user -d user_service"]
      interval: 10s
      retries: 5
      timeout: 5s
  user-service:
    image: user-service
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy  # Wait for PostgreSQL to be ready
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/user_service
      SPRING_DATASOURCE_USERNAME: micro_user
      SPRING_DATASOURCE_PASSWORD: Thanishka@5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
